jobs:
  include:
    - stage: test
      language: swift
      os: osx
      osx_image: xcode12.5 # Swift 5.4
      script:
      - swift --version
      - swift build
      - swift test --filter BitByteDataTests
      - swift build -c release # Check Release build just in case.
      - xcodebuild -version
      - xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=OS X" clean test
      - xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=iOS Simulator,name=iPhone 8" clean test
      # Since Xcode 12.5 watchos supports testing.
      - xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm" clean test
      - xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=tvOS Simulator,name=Apple TV" clean test
