trigger:
  branches:
    exclude:
    - master
  tags:
    include:
    - '*'

stages:
- stage: test
  displayName: 'Build & Test'
  jobs:
  - job: macos
    strategy:
      matrix:
        macosSwift50:
          imageName: 'macOS-10.14'
          DEVELOPER_DIR: '/Applications/Xcode_10.3.app'
        macosSwift51:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.3.1.app'
        macosSwift52:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.4.1.app'
        macosSwift53:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_12.4.app'
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
    - script: |
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=OS X" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=iOS Simulator,name=iPhone 8" clean test
      # For Swift 5.3 watchOS simulator is called differently.
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" clean build
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=tvOS Simulator,name=Apple TV" clean test
      displayName: 'Build & Test Darwin Platforms'
  - job: linux
    strategy:
      matrix:
        linuxSwift50:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.0.3'
        linuxSwift51:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.1.5'
        linuxSwift52:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.2.5'
        linuxSwift53:
          imageName: 'ubuntu-20.04'
          SWIFT_VERSION: '5.3.3'
    pool:
      vmImage: $(imageName)
    steps:
    - script: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      displayName: 'Install Swift'
    - script: |
        export SWIFTENV_ROOT="$HOME/.swiftenv"
        export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        export SWIFTENV_ROOT="$HOME/.swiftenv"
        export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
# - stage: Deploy
#   dependsOn: Test
#   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags') # Deploy on tags only
