trigger:
  branches:
    exclude:
    - master
  tags:
    include:
    - '*'
    exclude:
    - '*-test*'

stages:
- stage: test
  displayName: 'Build & Test'
  jobs:
  - job: macos
    strategy:
      matrix:
        macosSwift50:
          imageName: 'macOS-10.14'
          DEVELOPER_DIR: '/Applications/Xcode_10.3.app'
          WATCHOS_ACTIONS: 'clean build'
          WATCHOS_SIMULATOR: 'Apple Watch Series 4 - 44mm'
        macosSwift51:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.3.1.app'
          WATCHOS_ACTIONS: 'clean build'
          WATCHOS_SIMULATOR: 'Apple Watch Series 4 - 44mm'
        macosSwift52:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.4.1.app'
          WATCHOS_ACTIONS: 'clean build'
          WATCHOS_SIMULATOR: 'Apple Watch Series 4 - 44mm'
        macosSwift53:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_12.4.app'
          WATCHOS_ACTIONS: 'clean build'
          WATCHOS_SIMULATOR: 'Apple Watch Series 4 - 44mm'
        macosSwift54:
          imageName: 'macOS-11'
          DEVELOPER_DIR: '/Applications/Xcode_12.5.1.app'
          WATCHOS_ACTIONS: 'clean test'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 - 44mm'
        macosSwift55:
          imageName: 'macOS-11'
          DEVELOPER_DIR: '/Applications/Xcode_13.2.app'
          WATCHOS_ACTIONS: 'clean test'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 - 44mm'
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        set -e -o xtrace
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        set -e -o xtrace
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
    - script: |
        set -e -o xtrace
        xcodebuild -version
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=OS X" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=iOS Simulator,name=iPhone 8" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=watchOS Simulator,name=$WATCHOS_SIMULATOR" $WATCHOS_ACTIONS
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=tvOS Simulator,name=Apple TV" clean test
      displayName: 'Build & Test Darwin Platforms'
  - job: linux
    strategy:
      matrix:
        linuxSwift50:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.0.3-bionic'
        linuxSwift51:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.1.5-bionic'
        linuxSwift52:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.2.5-bionic'
        linuxSwift53:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.3.3-bionic'
        linuxSwift54:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.4.3-bionic'
        linuxSwift55:
          imageName: 'ubuntu-18.04'
          containerImage: 'swift:5.5.2-bionic'
    pool:
      vmImage: $(imageName)
    container: $[ variables['containerImage'] ]
    steps:
    - script: |
        set -e -o xtrace
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        set -e -o xtrace
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
  - job: windows
    strategy:
      matrix:
        windowsSwift54:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.4.3'
        windowsSwift55:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.5.1'
    pool:
      vmImage: $(imageName)
    variables:
      DEVELOPER_DIR: 'C:\Library\Developer'
      SDKROOT: 'C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk'
      XCTEST_DIR: 'C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development'
      SWIFTFLAGS: '--sdk $(SDKROOT)'
      SWIFTTESTFLAGS: '-Xswiftc -I -Xswiftc $(XCTEST_DIR)\usr\lib\swift\windows\x86_64 -Xswiftc -L -Xswiftc $(XCTEST_DIR)\usr\lib\swift\windows -Xswiftc -sdk -Xswiftc $(SDKROOT)'
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vsvarsall.bat'
    - pwsh: Invoke-WebRequest -Uri https://swift.org/builds/swift-$(SWIFT_VERSION)-release/windows10/swift-$(SWIFT_VERSION)-RELEASE/swift-$(SWIFT_VERSION)-RELEASE-windows10.exe -OutFile swift-install.exe
      displayName: 'Download Swift'
    - task: BatchScript@1
      inputs:
        filename: .\swift-install.exe
        arguments: /install /quiet
        modifyEnvironment: true
      displayName: 'Install Swift'
    - script: |
        copy %SDKROOT%\usr\share\ucrt.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
        copy %SDKROOT%\usr\share\visualc.modulemap "%VCToolsInstallDir%\include\module.modulemap"
        copy %SDKROOT%\usr\share\visualc.apinotes "%VCToolsInstallDir%\include\visualc.apinotes"
        copy %SDKROOT%\usr\share\winsdk.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
      displayName: 'Configure SDK'
    - script: |
        set PATH=C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin;C:\Library\Swift-development\bin;C:\Library\icu-67\usr\bin;%PATH%
        swift.exe --version
        swift.exe build %SWIFTFLAGS%
        swift.exe test --filter BitByteDataTests %SWIFTFLAGS% %SWIFTTESTFLAGS%
      displayName: 'Build & Test'
    - script: |
        set PATH=C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin;C:\Library\Swift-development\bin;C:\Library\icu-67\usr\bin;%PATH%
        swift.exe --version
        swift.exe build -c release %SWIFTFLAGS%
      displayName: 'Build Release'
- stage: deploy
  displayName: Deploy
  dependsOn: test
  # Deploy on tags only; test tags are excluded in trigger section.
  condition: and(not(eq(variables['Build.Reason'], 'PullRequest')), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
  jobs:
  - job: ghPages
    displayName: 'Publish API docs to GH Pages'
    pool:
      vmImage: 'macOS-10.15'
    variables:
      DEVELOPER_DIR: '/Applications/Xcode_12.4.app'
    steps:
    - script: |
        set -e -o xtrace
        brew update
        brew install sourcekitten
        gem install -N jazzy
      displayName: 'Install Tools'
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
        sshPublicKey: '$(bbdPubDeployKey)'
        sshKeySecureFile: 'bbd_deploy_key'
      displayName: 'Install an SSH key'
    - script: git worktree add docs gh-pages
      displayName: 'Prepare Worktree'
    - script: |
        sourcekitten doc --spm --module-name BitByteData > docs.json
        jazzy
      displayName: 'Before Deploy'
    - script: |
        set -e -o xtrace
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
        cd docs
        git add --all
        git commit -m "Deploy to GH Pages [skip ci]" --amend
        cd ..
        git remote set-url --push origin git@github.com:tsolomko/BitByteData.git
        git push --force origin gh-pages:gh-pages
      displayName: 'Deploy to GH Pages'
